In [4]:
import numpy as np
array_0d = np.array(2)
print(array_0d)

array_1d = np.array([1, 2, 3])
print(array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

array_1d.ndim

array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(array_3d)
print("Number of dimensions:", array_3d.ndim)


2
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions: 3


In [6]:
temperatures = [[75.2,77.1,74.5,79.3,82.6,81.2,77.8], [78,88,76,75,79,70,72]]

temperatures_array = np.array(temperatures)
print("Temperatures array:")


Temperatures array:


In [9]:
# Reshape the array
reshaped_temperatures = temperatures_array.reshape(2, 7)
print("Reshaped temperatures array:\n", reshaped_temperatures)

# Transpose the array
transposed_temperatures = temperatures_array.transpose()
print("Transposed temperatures array:\n", transposed_temperatures)

# Flatten the array
flattened_temperatures = temperatures_array.flatten()
print("Flattened temperatures array:", flattened_temperatures)


Reshaped temperatures array:
 [[75.2 77.1 74.5 79.3 82.6 81.2 77.8]
 [78.  88.  76.  75.  79.  70.  72. ]]
Transposed temperatures array:
 [[75.2 78. ]
 [77.1 88. ]
 [74.5 76. ]
 [79.3 75. ]
 [82.6 79. ]
 [81.2 70. ]
 [77.8 72. ]]
Flattened temperatures array: [75.2 77.1 74.5 79.3 82.6 81.2 77.8 78.  88.  76.  75.  79.  70.  72. ]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Addition
add_result = np.add(a, b)
print("Addition:", add_result)

# Subtraction
sub_result = np.subtract(a, b)
print("Subtraction:", sub_result)

# Multiplication
mul_result = np.multiply(a, b)
print("Multiplication:", mul_result)

# Division
div_result = np.divide(a, b)
print("Division:", div_result)

# Power
pow_result = np.power(a, 2)
print("Power (a squared):", pow_result)


Addition: [11 22 33 44]
Subtraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Power (a squared): [ 1  4  9 16]


In [12]:
np.arange(15).reshape(3,5)  





array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
np.ones((2,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.arange(0,5,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8])

In [17]:

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# Mean
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean_value = np.mean(data)
print("Mean:", mean_value)

# Median
median_value = np.median(data)
print("Median:", median_value)

# Standard Deviation
std_value = np.std(data)
print("Standard Deviation:", std_value)

# Variance
var_value = np.var(data)
print("Variance:", var_value)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


Problem Statement:
Consider the following arrays:

1. Arrays for Arithmetic Operations:

Array A: [15, 25, 35, 45, 55]
Array B: [5, 10, 15, 20, 25]
Array for Statistical Operations:

Array C: [12, 22, 32, 42, 52, 62, 72, 82, 92, 102]
Arrays for String Functions:

String Array X: ['Hello', 'Data', 'Science', 'Class', 'Learners']
String Array Y: ['World', 'Analysis', 'is', 'Fun', '2023']
Steps to Perform:

Perform element-wise addition, subtraction, multiplication, division, and power operations on Arrays A and B
Calculate the median, mean, standard deviation, and variance for Array C
Concatenate corresponding elements of String Arrays X and Y
Convert all elements in String Array X to uppercase
Replace a specific substring in String Array Y with another substring

In [21]:
A = np.array([15, 25, 35, 45, 55])
B = np.array([5, 10, 15, 20, 25])

add_AB = np.add(A, B)
print("Addition of A and B:", add_AB)

sub_AB = np.subtract(A, B)
print("Subtraction of A and B:", sub_AB)

mul_AB = np.multiply(A, B)
print("Multiplication of A and B:", mul_AB)

div_AB = np.divide(A, B)
print("Division of A and B:", div_AB)

pow_AB = np.power(A, 2)
print("Power of A (A squared):", pow_AB)



Addition of A and B: [20 35 50 65 80]
Subtraction of A and B: [10 15 20 25 30]
Multiplication of A and B: [  75  250  525  900 1375]
Division of A and B: [3.         2.5        2.33333333 2.25       2.2       ]
Power of A (A squared): [ 225  625 1225 2025 3025]


In [ ]:
C = np.array([12, 22, 32, 42, 52, 62, 72, 82, 92, 102])

mean_c = np.mean(C)
print("Mean of C:", mean_c)

median_c = np.median(C)
print("Median of C:", median_c)

std_c = np.std(C)
print("Standard Deviation of C:", std_c)

var_c = np.var(C)
print("Variance of C:", var_c)



In [27]:
X = np.array(['Hello', 'Data', 'Science', 'Class', 'Learners'])
Y = np.array(['World', 'Analysis', 'is', 'Fun', '2023'])

# Concatenate corresponding elements of String Arrays X and Y with a space
concatenated_strings = np.char.add(X, np.char.add(' ', Y))
print("Concatenated Strings:", concatenated_strings)

# Convert all strings in X to uppercase
uppercase_X = np.char.upper(X)
print("Uppercase X:", uppercase_X)

# Replace a specific substring in String Array Y with another substring
replaced_Y = np.char.replace(Y, 'is', 'are')
print("Replaced Y:", replaced_Y)

Concatenated Strings: ['Hello World' 'Data Analysis' 'Science is' 'Class Fun' 'Learners 2023']
Uppercase X: ['HELLO' 'DATA' 'SCIENCE' 'CLASS' 'LEARNERS']
Replaced Y: ['World' 'Analysare' 'are' 'Fun' '2023']


Assisted Practice
Problem Statement:
Create a 1D NumPy array with at least 10 elements
Create a 2D NumPy array with a minimum of 3 rows and 4 columns
Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
Accessing Elements in Arrays
Access and print various elements from 1D, 2D, and, 3D using positive indexing
Perform and print some basic arithmetic operations (like addition, subtraction) using elements accessed from 1D, 2D, and, 3D arrays
Access and print elements using negative indices in all three arrays

In [ ]:
# 1D array with at least 10 elements
import numpy as np
arr_1d = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
print("1D Array:", arr_1d)

# 2D array with 3 rows and 4 columns
arr_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("2D Array:\n", arr_2d)

# 3D array: 2 matrices, each 2x3
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("3D Array:\n", arr_3d)

# Access
print("1D, 3rd element:", arr_1d[2])
print("2D, 2nd row, 3rd column:", arr_2d[1, 2])
print("3D, 2nd matrix, 1st row, 2nd column:", arr_3d[1, 0, 1])

# Arithmetic operations
add_result = arr_1d[0] + arr_2d[0, 0] + arr_3d[0, 0, 0]
print("Addition of first elements from each array:", add_result)

sub_result = arr_1d[1] - arr_2d[1, 1] - arr_3d[1, 1, 1]
print("Subtraction of elements:", sub_result)

# Accessing elements using negative indexing
print("1D, last element:", arr_1d[-1])
print("2D, last row, last column:", arr_2d[-1, -1])
print("3D, last matrix, last row, last column:", arr_3d[-1, -1, -1])

1D Array: [ 5 10 15 20 25 30 35 40 45 50]
2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1D, 3rd element: 15
2D, 2nd row, 3rd column: 7
3D, 2nd matrix, 1st row, 2nd column: 8
Addition of first elements from each array: 7
Subtraction of elements: -7
1D, last element: 50
2D, last row, last column: 12
3D, last matrix, last row, last column: 12
