In [4]:
import numpy as np
array_0d = np.array(2)
print(array_0d)

array_1d = np.array([1, 2, 3])
print(array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

array_1d.ndim

array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(array_3d)
print("Number of dimensions:", array_3d.ndim)


2
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions: 3


In [6]:
temperatures = [[75.2,77.1,74.5,79.3,82.6,81.2,77.8], [78,88,76,75,79,70,72]]

temperatures_array = np.array(temperatures)
print("Temperatures array:")


Temperatures array:


In [9]:
# Reshape the array
reshaped_temperatures = temperatures_array.reshape(2, 7)
print("Reshaped temperatures array:\n", reshaped_temperatures)

# Transpose the array
transposed_temperatures = temperatures_array.transpose()
print("Transposed temperatures array:\n", transposed_temperatures)

# Flatten the array
flattened_temperatures = temperatures_array.flatten()
print("Flattened temperatures array:", flattened_temperatures)


Reshaped temperatures array:
 [[75.2 77.1 74.5 79.3 82.6 81.2 77.8]
 [78.  88.  76.  75.  79.  70.  72. ]]
Transposed temperatures array:
 [[75.2 78. ]
 [77.1 88. ]
 [74.5 76. ]
 [79.3 75. ]
 [82.6 79. ]
 [81.2 70. ]
 [77.8 72. ]]
Flattened temperatures array: [75.2 77.1 74.5 79.3 82.6 81.2 77.8 78.  88.  76.  75.  79.  70.  72. ]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Addition
add_result = np.add(a, b)
print("Addition:", add_result)

# Subtraction
sub_result = np.subtract(a, b)
print("Subtraction:", sub_result)

# Multiplication
mul_result = np.multiply(a, b)
print("Multiplication:", mul_result)

# Division
div_result = np.divide(a, b)
print("Division:", div_result)

# Power
pow_result = np.power(a, 2)
print("Power (a squared):", pow_result)


Addition: [11 22 33 44]
Subtraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Power (a squared): [ 1  4  9 16]


In [12]:
np.arange(15).reshape(3,5)  





array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
np.ones((2,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.arange(0,5,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8])

In [17]:

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])