In [4]:
import numpy as np
array_0d = np.array(2)
print(array_0d)

array_1d = np.array([1, 2, 3])
print(array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

array_1d.ndim

array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(array_3d)
print("Number of dimensions:", array_3d.ndim)


2
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions: 3
