In [4]:
import numpy as np
array_0d = np.array(2)
print(array_0d)

array_1d = np.array([1, 2, 3])
print(array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

array_1d.ndim

array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(array_3d)
print("Number of dimensions:", array_3d.ndim)


2
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions: 3


In [6]:
temperatures = [[75.2,77.1,74.5,79.3,82.6,81.2,77.8], [78,88,76,75,79,70,72]]

temperatures_array = np.array(temperatures)
print("Temperatures array:")


Temperatures array:


In [9]:
# Reshape the array
reshaped_temperatures = temperatures_array.reshape(2, 7)
print("Reshaped temperatures array:\n", reshaped_temperatures)

# Transpose the array
transposed_temperatures = temperatures_array.transpose()
print("Transposed temperatures array:\n", transposed_temperatures)

# Flatten the array
flattened_temperatures = temperatures_array.flatten()
print("Flattened temperatures array:", flattened_temperatures)


Reshaped temperatures array:
 [[75.2 77.1 74.5 79.3 82.6 81.2 77.8]
 [78.  88.  76.  75.  79.  70.  72. ]]
Transposed temperatures array:
 [[75.2 78. ]
 [77.1 88. ]
 [74.5 76. ]
 [79.3 75. ]
 [82.6 79. ]
 [81.2 70. ]
 [77.8 72. ]]
Flattened temperatures array: [75.2 77.1 74.5 79.3 82.6 81.2 77.8 78.  88.  76.  75.  79.  70.  72. ]
