In [11]:
import numpy as np


arr = np.array([10, 20, 30, 40, 50, 60, 70])

print("Elements from index 1 to 4:", arr[1:5])        # [20 30 40 50]
print("Every second element:", arr[::2])              # [10 30 50 70]
print("Last three elements:", arr[-3:])               # [50 60 70]

arr2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("First two rows:\n", arr2d[:2, :])
print("Last two columns:\n", arr2d[:, -2:])
print("Submatrix (rows 1-2, cols 2-3):\n", arr2d[0:2, 1:3])

Elements from index 1 to 4: [20 30 40 50]
Every second element: [10 30 50 70]
Last three elements: [50 60 70]
First two rows:
 [[1 2 3 4]
 [5 6 7 8]]
Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]]
Submatrix (rows 1-2, cols 2-3):
 [[2 3]
 [6 7]]


In [12]:
import numpy as np


In [13]:
# 1D array with at least 15 elements
array_1d = np.arange(1, 16)

In [14]:
# 2D array with at least 4 rows and 5 columns
array_2d = np.arange(1, 21).reshape(4, 5)

In [15]:
# 3D array with 2 matrices, each with 3 rows and 4 columns
array_3d = np.arange(1, 25).reshape(2, 3, 4)

In [16]:
slice_1d_1 = array_1d[0:5]          # First 5 elements
slice_1d_2 = array_1d[5:10]         # Middle 5 elements
slice_1d_3 = array_1d[::2]          # Every 2nd element
slice_1d_4 = array_1d[1::3]         # Every 3rd element starting from index 1
slice_1d_5 = array_1d[::-1]         # Reversed array (negative slicing)

print("1D Array Slices:")
print("First 5 elements:", slice_1d_1)
print("Middle 5 elements:", slice_1d_2)
print("Every 2nd element:", slice_1d_3)
print("Every 3rd element starting from index 1:", slice_1d_4)
print("Reversed array:", slice_1d_5)



1D Array Slices:
First 5 elements: [1 2 3 4 5]
Middle 5 elements: [ 6  7  8  9 10]
Every 2nd element: [ 1  3  5  7  9 11 13 15]
Every 3rd element starting from index 1: [ 2  5  8 11 14]
Reversed array: [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [17]:
slice_2d_1 = array_2d[1]            # Second row
slice_2d_2 = array_2d[:, 2]         # Third column
slice_2d_3 = array_2d[1:3, 2:5]     # Rows 1-2 and Columns 2-4
slice_2d_4 = array_2d[::-1]         # Reversed rows
slice_2d_5 = array_2d[:, ::-1]      # Reversed columns
print("\n2D Array Slices:")
print("Second row:", slice_2d_1)
print("Third column:", slice_2d_2)
print("Rows 1-2 and Columns 2-4:\n", slice_2d_3)
print("Reversed rows:\n", slice_2d_4)
print("Reversed columns:\n", slice_2d_5)


2D Array Slices:
Second row: [ 6  7  8  9 10]
Third column: [ 3  8 13 18]
Rows 1-2 and Columns 2-4:
 [[ 8  9 10]
 [13 14 15]]
Reversed rows:
 [[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
Reversed columns:
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]


In [18]:

slice_3d_1 = array_3d[0]            # First matrix
slice_3d_2 = array_3d[1, 1]         # Second matrix, second row
slice_3d_3 = array_3d[1, 1, 2]      # Specific element: matrix 1, row 1, col 2
slice_3d_4 = array_3d[::-1]         # Reverse matrices
slice_3d_5 = array_3d[:, ::-1]      # Reverse rows in each matrix
slice_3d_6 = array_3d[:, :, ::-1]   # Reverse columns in each row of each matrix
print("\n3D Array Slices:")
print("First matrix:\n", slice_3d_1)
print("Second matrix, second row:", slice_3d_2)
print("Specific element (matrix 1, row 1, col 2):", slice_3d_3)
print("Reversed matrices:\n", slice_3d_4)
print("Reversed rows in each matrix:\n", slice_3d_5)
print("Reversed columns in each row of each matrix:\n", slice_3d_6)



3D Array Slices:
First matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second matrix, second row: [17 18 19 20]
Specific element (matrix 1, row 1, col 2): 19
Reversed matrices:
 [[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Reversed rows in each matrix:
 [[[ 9 10 11 12]
  [ 5  6  7  8]
  [ 1  2  3  4]]

 [[21 22 23 24]
  [17 18 19 20]
  [13 14 15 16]]]
Reversed columns in each row of each matrix:
 [[[ 4  3  2  1]
  [ 8  7  6  5]
  [12 11 10  9]]

 [[16 15 14 13]
  [20 19 18 17]
  [24 23 22 21]]]
