Recurrent Neural Network
Rnn has memory is the biggest difference 
Rnn is used in NLP
it keeps past in consideration , sequential data such as timeseries etc.


In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
import matplotlib.pyplot as plt


In [4]:
np.random.seed(40)
data = np.random.randint(100,200, size =200)
data

array([170, 191, 107, 137, 156, 150, 165, 112, 171, 119, 131, 174, 155,
       183, 159, 191, 173, 196, 149, 153, 173, 108, 152, 130, 179, 114,
       192, 158, 174, 122, 103, 191, 199, 171, 155, 183, 128, 113, 137,
       182, 150, 179, 167, 130, 160, 144, 146, 187, 143, 135, 198, 131,
       182, 105, 180, 165, 107, 192, 141, 199, 195, 188, 193, 125, 183,
       158, 198, 170, 157, 157, 183, 185, 136, 163, 174, 188, 100, 101,
       133, 152, 172, 157, 134, 114, 178, 171, 156, 177, 186, 184, 182,
       191, 112, 190, 173, 127, 100, 121, 194, 132, 151, 150, 120, 141,
       178, 155, 147, 143, 191, 176, 129, 145, 107, 110, 161, 119, 168,
       125, 161, 198, 116, 188, 161, 151, 188, 141, 158, 121, 131, 195,
       143, 168, 116, 103, 115, 179, 104, 106, 194, 166, 185, 151, 190,
       183, 102, 109, 106, 139, 125, 156, 117, 113, 107, 150, 196, 148,
       153, 100, 138, 160, 148, 167, 197, 161, 145, 161, 110, 177, 157,
       152, 140, 101, 152, 158, 188, 122, 148, 124, 158, 193, 17

In [5]:
#prepare input sequences (x = past 7 days)
#labels y = next day
def prepare_data(data, sequence_length = 7):
    x, y = [], []
    for i in range(len(data) - sequence_length):
        x.append(data[i:i + sequence_length])
        y.append(data[i + sequence_length])
    return np.array(x), np.array(y)

In [8]:
X, y = prepare_data(data)

In [9]:
X

array([[170, 191, 107, ..., 156, 150, 165],
       [191, 107, 137, ..., 150, 165, 112],
       [107, 137, 156, ..., 165, 112, 171],
       ...,
       [196, 102, 164, ..., 179, 194, 110],
       [102, 164, 175, ..., 194, 110, 115],
       [164, 175, 179, ..., 110, 115, 197]])

In [10]:
y

array([112, 171, 119, 131, 174, 155, 183, 159, 191, 173, 196, 149, 153,
       173, 108, 152, 130, 179, 114, 192, 158, 174, 122, 103, 191, 199,
       171, 155, 183, 128, 113, 137, 182, 150, 179, 167, 130, 160, 144,
       146, 187, 143, 135, 198, 131, 182, 105, 180, 165, 107, 192, 141,
       199, 195, 188, 193, 125, 183, 158, 198, 170, 157, 157, 183, 185,
       136, 163, 174, 188, 100, 101, 133, 152, 172, 157, 134, 114, 178,
       171, 156, 177, 186, 184, 182, 191, 112, 190, 173, 127, 100, 121,
       194, 132, 151, 150, 120, 141, 178, 155, 147, 143, 191, 176, 129,
       145, 107, 110, 161, 119, 168, 125, 161, 198, 116, 188, 161, 151,
       188, 141, 158, 121, 131, 195, 143, 168, 116, 103, 115, 179, 104,
       106, 194, 166, 185, 151, 190, 183, 102, 109, 106, 139, 125, 156,
       117, 113, 107, 150, 196, 148, 153, 100, 138, 160, 148, 167, 197,
       161, 145, 161, 110, 177, 157, 152, 140, 101, 152, 158, 188, 122,
       148, 124, 158, 193, 174, 189, 196, 143, 164, 171, 106, 14

In [11]:
X = X.reshape((X.shape[0], X.shape[1], 1))  # Reshape for RNN input
X.shape


(193, 7, 1)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [13]:
#build the RNN model
rnnmodel = Sequential()
rnnmodel.add(SimpleRNN(50, activation='relu', input_shape=(X_train.shape[1], 1)))
rnnmodel.add(Dense(1))  # Output layer for regression

rnnmodel.compile(optimizer='adam', loss='mse')
#train the model
history = rnnmodel.fit(X_train, y_train, epochs=30, verbose=1)

Epoch 1/30
5/5 [==============================] - 11s 47ms/step - loss: 22427.3711
Epoch 2/30
5/5 [==============================] - 0s 9ms/step - loss: 11624.5293
Epoch 3/30
5/5 [==============================] - 0s 48ms/step - loss: 3536.1685
Epoch 4/30
5/5 [==============================] - 0s 34ms/step - loss: 1187.8176
Epoch 5/30
5/5 [==============================] - 0s 7ms/step - loss: 2088.6077
Epoch 6/30
5/5 [==============================] - 0s 19ms/step - loss: 1159.4561
Epoch 7/30
5/5 [==============================] - 0s 19ms/step - loss: 1069.6205
Epoch 8/30
5/5 [==============================] - 0s 19ms/step - loss: 1156.4768
Epoch 9/30
5/5 [==============================] - 0s 13ms/step - loss: 1009.4692
Epoch 10/30
5/5 [==============================] - 0s 14ms/step - loss: 940.2363
Epoch 11/30
5/5 [==============================] - 0s 20ms/step - loss: 987.8776
Epoch 12/30
5/5 [==============================] - 0s 39ms/step - loss: 941.5296
Epoch 13/30
5/5 [==========

In [14]:
y_pred  = rnnmodel.predict(X_test)

2/2 [==============================] - 2s 18ms/step
